[package]
name = "tdigest_core"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = ["bindings/python"]

[dependencies]
anyhow = "1.0.79"
itertools = "0.13.0"
num = "0.4.1"
num-traits = "0.2.19"
