[package]
name = "tdigest_core"
version = "0.2.0"
edition = "2021"

[workspace]
resolver = "2"
members = ["bindings/python"]

[dependencies]
anyhow = "1.0.93"
itertools = "0.14.0"
num = "0.4.3"
num-traits = "0.2.19"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "benchmarks"
harness = false
