[package]
name = "tdigest_rs"
version = "0.3.0"
edition = "2021"

[lib]
name = "tdigest_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27", features = [
    "extension-module",
    "abi3-py310",
    "anyhow",
] }
numpy = "0.27"
ndarray = "0.17"
tdigest_core = { version = "0.3.0", path = "../../" }
