name: CI

on:
  push:
  pull_request:
  schedule:
    # Run daily at 02:43 so we get notified if CI is broken before a pull request
    # is submitted.
    - cron: "43 2 * * *"

jobs:
  rust:
    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    uses: ./.github/workflows/rust.yml

  python:
    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    uses: ./.github/workflows/python.yml

  # Virtual job that can be configured as a required check before a PR can be merged.
  # As GitHub considers a check as successful if it is skipped, we need to check its status in
  # another workflow (check-required.yml) and create a check there.
  all-required-checks-done:
    name: All required checks done
    runs-on: ubuntu-latest
    needs:
      - rust
      - python
    steps:
      - run: echo "All required checks done"

  release:
    if: ${{ !github.event.repository.fork && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
    needs: all-required-checks-done
    permissions:
      actions: write
      contents: write
      id-token: write
    secrets: inherit
    uses: ./.github/workflows/release.yml
