name: Nudge

on:
  workflow_run:
    workflows: ["CI", "Create release"]
    types: [completed]
    branches: [main]

jobs:
  nudge:
    runs-on: ubuntu-latest
    environment: nudge
    steps:
      - name: Send message
        uses: pavlovic-ivan/octo-nudge@main
        with:
          webhooks: ${{ secrets.WEBHOOKS }}