name: Python
on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  DEFAULT_PYTHON_VERSION: "3.12"
  UV_PROJECT_ENVIRONMENT: .venv

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.DEFAULT_PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
          check-latest: true
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Sync Python dependencies
        run: uv sync --all-groups --project bindings/python
      - name: Lint
        run: |
          uv run --project bindings/python ruff check bindings/python
          uv run --project bindings/python ruff format --check bindings/python
          uv run --project bindings/python mypy --config-file bindings/python/pyproject.toml bindings/python/tdigest_rs

  test:
    name: Test
    strategy:
      matrix:
        python-version: ["3.12"]
        runner: [ubuntu-latest, macos-14, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Sync Python dependencies
        run: uv sync --all-groups --project bindings/python
      - name: Build Python extension
        run: uv run --project bindings/python maturin develop -F python
      - name: Test
        run: uv run --project bindings/python pytest -q bindings/python/tests/test_api_python.py

  build:
    name: Build
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - runner: ubuntu-latest
            target: aarch64-unknown-linux-musl
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - runner: macos-14
            target: aarch64-apple-darwin
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release
          manylinux: auto
          target: ${{ matrix.target }}
          working-directory: bindings/python
      - name: Upload Python Package
        uses: actions/upload-artifact@v4
        with:
          name: python-package-${{ matrix.target }}
          path: target/wheels/*.whl
