name: Python
on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  DEFAULT_PYTHON_VERSION: "3.12"
  PIP_DISABLE_PIP_VERSION_CHECK: 1

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.DEFAULT_PYTHON_VERSION }}
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
          check-latest: true
      - name: Lint
        run: pipx run --python '${{ steps.setup-python.outputs.python-path }}' hatch run dev:lint
        working-directory: bindings/python

  test:
    name: Test
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        runner: [ubuntu-latest, macos-13, macos-14, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true
      # pipx currently has permissions issues on macOS 14 arm64 runners
      # see https://github.com/actions/runner-images/issues/9256
      - name: Fix pipx permissions
        if: matrix.runner == 'macos-14'
        run: |
          for dir in "$PIPX_HOME" "$PIPX_BIN_DIR"; do
            if [ -n "$dir" ]; then
              sudo mkdir -p "$dir"
              sudo chown -R $(id -u) "$dir"
            fi
          done
      - name: Test
        run: pipx run --python '${{ steps.setup-python.outputs.python-path }}' hatch run dev:test
        working-directory: bindings/python

  build:
    name: Build
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - runner: ubuntu-latest
            target: aarch64-unknown-linux-musl
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - runner: macos-13
            target: x86_64-apple-darwin
          - runner: macos-14
            target: aarch64-apple-darwin
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release
          manylinux: auto
          target: ${{ matrix.target }}
          working-directory: bindings/python
      - name: Upload Python Package
        uses: actions/upload-artifact@v4
        with:
          name: python-package-${{ matrix.target }}
          path: target/wheels/*.whl
