name: Rust

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clippy
        run: cargo clippy --verbose
      - name: Format check
        run: cargo fmt --verbose --check

  test:
    name: Test
    strategy:
      matrix:
        # macos-13 is x86_64 and macos-14 is arm64
        runner: [ubuntu-latest, macos-13, macos-14, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose
